version: 2
jobs:
  build:
    docker:
      - image: adeln/phoenix:latest
        # environment:
        #   MIX_ENV: test
      - image: postgres:alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout  # check out source code to working directory
      
      - restore_cache:
          keys:
            - mix-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - build
      - restore_cache:
          keys:
            - plts

      - run: mix do deps.get, compile, dialyzer

      - save_cache:
          key: mix-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: build
          paths: "_build"
      - save_cache:
          key: plts
          paths: "priv/plts"

      - run: mix test

      - store_test_results:
          path: _build/test/lib/liveproxy
